favicon: null
name: Rob Karman Photography
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
purpose: []
color:
  saturation: 0.7275985
  brandStrength: 0.02206110488623381
  lightness: 0
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  rhythmicContrast: 0.327957
typography_spectrum: 0.9759794743731618
cta:
  bucket: null
  version: null
  domain: null
layout_spectrum: 0.6083816925529391
analytics:
  twitter: null
  google: null
  facebook: null
